### ISSUE TITLE
Exception On Exit

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#132]
Windows only. Happens on every exit with either `exit` or `exit-nosave`.
```
Unhandled Exception: System.EntryPointNotFoundException: Entry point was not found.
   at System.IDisposable.Dispose()
   at Terraria.Program.LaunchGame(String[] args)
   at Terraria.WindowsLaunch.Main(String[] args)
```

**Comment by D1G1T4L3CH0** [comment]
Resolved.
