### ISSUE TITLE
Conflict in Nat mapping

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#191]
Don't use port 0 heh.
```
Terraria Server v1.3.0.8

Listening on port 0
Type 'help' for a list of commands.

8/21/2015 12:24:46 AM Command> Ready for commands.
8/21/2015 12:24:46 AM Pool> Failed to create NAT device mapping:
Mono.Nat.MappingException: Error 718: ConflictInMappingEntry
   at Mono.Nat.Upnp.UpnpNatDevice.EndCreatePortMap(IAsyncResult result)
   at Mono.Nat.AbstractNatDevice.CreatePortMap(Mapping mapping)
   at TDSM.API.Callbacks.NAT.NatUtility_DeviceFound(Object sender, DeviceEventArgs e)
```

**Comment by DeathCradle** [comment]
Decided to remove NAT from OTA & TDSM. A plugin can achieve this.
