### ISSUE TITLE
Crash on /whoami

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#207]
Brand new database file created. First startup, first connection.

I connected.
```
127.0.0.1:49766 is connecting...
9/24/2015 4:07:22 PM Pool> ArgsPool<RecvArgs> capacity is now: 1.
9/24/2015 4:07:22 PM Pool> ArgsPool<SendArgs> capacity is now: 1.
9/24/2015 4:07:23 PM Pool> 127.0.0.1:49766 @ 0: ENTER D1G1T4L3CH0
D1G1T4L3CH0 has joined.
```

Added user from console.
```
user add D1G1T4L3CH0 1212
9/24/2015 4:07:44 PM Command> Successfully created user D1G1T4L3CH0
```

Added myself to the Admin group.
```
user addgroup D1G1T4L3CH0 Admin
9/24/2015 4:07:55 PM Command> Successfully added D1G1T4L3CH0 to group Admin
```
Checking whoami to be sure everything is working as expected. It said I wasn't logged in and I am a part of the guest group.
```
9/24/2015 4:08:05 PM Pool> D1G1T4L3CH0 sent command: /whoami
```
Logging in.
```
9/24/2015 4:08:10 PM Pool> D1G1T4L3CH0 sent command: /auth 1212
9/24/2015 4:08:10 PM Pool> D1G1T4L3CH0 successfully logged in.
```
Checking whoami again. Got a crash...
```
9/24/2015 4:08:16 PM Pool> D1G1T4L3CH0 sent command: /whoami
9/24/2015 4:08:16 PM Pool> Plugin TDSM Core Module crashed in hook player-chat:
System.Data.Entity.Core.EntityCommandCompilationException: An error occurred while preparing the command definition. See the inner exception for details. ---> System.NotSupportedException: APPLY joins are not supported
   at System.Data.SQLite.EF6.SqlGenerator.Visit(DbApplyExpression e)
   at System.Data.Entity.Core.Common.CommandTrees.DbApplyExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.SQLite.EF6.SqlGenerator.VisitInputExpression(DbExpression inputExpression, String inputVarName, TypeUsage inputVarType, Symbol& fromSymbol)
   at System.Data.SQLite.EF6.SqlGenerator.Visit(DbProjectExpression e)
   at System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.SQLite.EF6.SqlGenerator.VisitExpressionEnsureSqlStatement(DbExpression e, Boolean addDefaultColumns)
   at System.Data.SQLite.EF6.SqlGenerator.Visit(DbLimitExpression e)
   at System.Data.Entity.Core.Common.CommandTrees.DbLimitExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.SQLite.EF6.SqlGenerator.VisitInputExpression(DbExpression inputExpression, String inputVarName, TypeUsage inputVarType, Symbol& fromSymbol)
   at System.Data.SQLite.EF6.SqlGenerator.Visit(DbProjectExpression e)
   at System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.SQLite.EF6.SqlGenerator.VisitExpressionEnsureSqlStatement(DbExpression e, Boolean addDefaultColumns)
   at System.Data.SQLite.EF6.SqlGenerator.VisitExpressionEnsureSqlStatement(DbExpression e)
   at System.Data.SQLite.EF6.SqlGenerator.GenerateSql(DbQueryCommandTree tree)
   at System.Data.SQLite.EF6.SqlGenerator.GenerateSql(SQLiteProviderManifest manifest, DbCommandTree tree, List`1& parameters, CommandType& commandType)
   at System.Data.SQLite.EF6.SQLiteProviderServices.CreateCommand(DbProviderManifest manifest, DbCommandTree commandTree)
   at System.Data.SQLite.EF6.SQLiteProviderServices.CreateDbCommandDefinition(DbProviderManifest manifest, DbCommandTree commandTree)
   at System.Data.Entity.Core.Common.DbProviderServices.CreateDbCommandDefinition(DbProviderManifest providerManifest, DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)
   at System.Data.Entity.Core.EntityClient.Internal.EntityProviderServices.CreateDbCommandDefinition(DbProviderManifest providerManifest, DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.CreateCommandDefinition(ObjectContext context, DbQueryCommandTree tree)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.Prepare(ObjectContext context, DbQueryCommandTree tree, Type elementType, MergeOption mergeOption, Boolean streaming, Span span, IEnumerable`1 compiledQueryParameters, AliasGenerator aliasGenerator)
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__1[TResult](IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at OTA.Data.Storage.IsPermitted(String prmNode, Boolean prmIsGuest, String prmAuthentication) in C:\Git\Open-Terraria-API\API\Data\IDataConnector.cs:line 280
   at OTA.Data.Storage.IsPermitted(String node, BasePlayer player) in C:\Git\Open-Terraria-API\API\Data\IDataConnector.cs:line 189
   at OTA.Command.CommandParser.CheckPermissions(ISender sender, CommandInfo cmd) in C:\Git\Open-Terraria-API\API\Command\CommandParser.cs:line 665
   at OTA.Command.CommandParser.CheckAccessLevel(CommandInfo cmd, ISender sender) in C:\Git\Open-Terraria-API\API\Command\CommandParser.cs:line 568
   at OTA.Command.CommandParser.ParseAndProcess(ISender sender, String line) in C:\Git\Open-Terraria-API\API\Command\CommandParser.cs:line 755
   at OTA.Command.CommandParser.ParsePlayerCommand(Player player, String line) in C:\Git\Open-Terraria-API\API\Command\CommandParser.cs:line 555
   at TDSM.Core.Entry.OnChat(HookContext& ctx, PlayerChat& args)
   at OTA.Plugin.HookPoint`1.Invoke(HookContext& context, T& arg) in C:\Git\Open-Terraria-API\API\Plugin\HookPoint.cs:line 367
```

**Comment by DeathCradle** [comment]
I think this is also fixed in the latest. When you get a sec it would be great if you could confirm.

Chat:
![screen shot 2015-11-09 at 2 05 02 pm](https://cloud.githubusercontent.com/assets/776327/11025730/0c792196-86eb-11e5-8173-3dc7557caaca.png)

Console: (cut off the top because didnt type the command right haha)
![screen shot 2015-11-09 at 2 05 08 pm](https://cloud.githubusercontent.com/assets/776327/11025731/182097b8-86eb-11e5-9a4c-cec8e535233d.png)
