### ISSUE TITLE
Can't add user to groups

### ISSUE THREAD

**Issue by Chupesmpx** [DeathCradle/Terraria-s-Dedicated-Server-Mod#213]
Whenever i try to add a user to a group i get an error that user can only be in one group, but the usser isnt associated with any groups.

>user addgroup Chuperto gen

>10/1/2015 1:17:58 AM Command> Exception from command
>10/1/2015 1:17:58 AM Command> System.NotSupportedException: A player can only be associated to one group, please assign a parent to the desired group
  >   at OTA.Data.Storage.AddUserToGroup(String username, String groupName)
  >   at TDSM.Core.Entry.UserPermission(ISender sender, ArgumentList args)
  > at OTA.Command.CommandInfo.Run(ISender sender, ArgumentList args)
  > at OTA.Command.CommandParser.ParseAndProcess(ISender sender, String line)
  > at OTA.Command.CommandParser.ParseConsoleCommand(String line, ConsoleSender sender)
  > at TDSM.Core.Entry.ListenForCommands()

>user listgroups Chuperto
>There are no registered groups for user Chuperto

**Comment by D1G1T4L3CH0** [comment]
Confirmed. Adding a new user and then immediately attempting to assign a group to the user results in the above exception.

**Comment by DeathCradle** [comment]
As per the new database, this might be fixed. This needs testing again.
